version: '3.8'

services:
  postgres:
    image: postgres
    container_name: linktree-pg-db
    restart: always
    environment:
      POSTGRES_DB: linktree
      POSTGRES_USER: linktree
      POSTGRES_PASSWORD: linkTree123
      POSTGRES_TIMEZONE: Asia/Tehran
      POSTGRES_SSLMODE: false
    ports:
      - "3010:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
      LOG_LEVEL: "debug"
      
volumes:
  postgres_data:
    driver: local